### ISSUE TITLE
Upgrade to version 4?

### ISSUE THREAD

**Issue by Sebastianbrg** [radibit/alfred-keycode#2]

**Comment by Sebastianbrg** [comment]
npm install -g alfred-keycode

> alfred-keycode@0.2.1 postinstall /Users/x/.nvm/versions/node/v13.6.0/lib/node_modules/alfred-keycode
> alfy-init

Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/x/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at /Users/x/.nvm/versions/node/v13.6.0/lib/node_modules/alfred-keycode/node_modules/resolve-alfred-prefs/index.js:15:10

    at /Users/x/.nvm/versions/node/v13.6.0/lib/node_modules/alfred-keycode/node_modules/alfy/node_modules/execa/index.js:201:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/x/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at /Users/x/.nvm/versions/node/v13.6.0/lib/node_modules/alfred-keycode/node_modules/resolve-alfred-prefs/index.js:15:10\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false
}

**Comment by chrisspiegl** [comment]
I think this would be great if updated.

**Comment by radibit** [comment]
@Sebastianbrg @chrisspiegl Thank you for the comments on this issue. With the latest release of `alfred-keycode` ([0.3.0](https://github.com/radibit/alfred-keycode/releases/tag/0.3.0)) support for Alfred 4 has been added, including a fix for the broken `alfred-link` feature.

**Comment by chrisspiegl** [comment]
Tested, works and the `npm install -g alfred-keycode` works perfectly as well.
Thank you ❤.
